apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-local-cert
  namespace: hml
spec:
  secretName: nginx-local-tls
  duration: 8760h # 1 ano
  renewBefore: 360h
  commonName: nginx.local
  dnsNames:
    - nginx.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
